version: "3.8"

services:
  redis:
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
    platform: linux/amd64
    ports:
      - "16379:6379"
    volumes:
      - $PWD/data:/data
    env_file:
      - .env

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    platform: linux/amd64
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env
    depends_on:
      - redis

  test_redis:
    build:
      context: ./
      dockerfile: docker/redis/Dockerfile
    platform: linux/amd64
    ports:
      - "26379:6379"
    env_file:
      - .env.test

  test:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    platform: linux/amd64
    volumes:
      - $PWD:/redis-sitesearch
    env_file:
      - .env.test
    depends_on:
      - test_redis
    entrypoint: "pytest"

