name: Reindex

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make a reindex API request
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          CODE=`curl --write-out '%{http_code}' --silent --output /dev/null -X POST -H "X-API-KEY: $API_TOKEN" -H "Content-Length: 0" https://search-service.redislabs.com/indexer`
          if [ $CODE!="200" ]
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
