name: Reindex

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make a reindex API request
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST -H "X-API-KEY: ${API_KEY}" -H "Content-Length: 0" https://search-service.redislabs.com/indexer
