name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sed -i 's/remove-if-redis-has-no-password/test/g' .env
      - run: cp .env.example .env
      - run: docker-compose up test
